#!/bin/bash

# Check the first argument and call appropriate script or function
case "$1" in
    -repo)
        shift
        exec gith-dl-repo "$@"
        ;;
    -gist)
        shift
        exec gith-dl-gist "$@"
        ;;
    uninstall)
        # Call uninstall function
        echo "[*] Uninstalling gith-dl..."
        bash "$(dirname "$0")/uninstall.sh"
        ;;
    *)
        echo "Usage: gith-dl -repo| -gist [args...] | uninstall"
        exit 1
        ;;
esac
